apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongodb
  
spec:
  serviceName: "mongodb"
  replicas: 1

  template:
    metadata:
      name: mongodb
      labels:
        name: mongodb
        group: databases

    spec:

      containers:
      - name: mongodb
        image: docker.io/darkxeno/mongodb-statefulset:4.1.3
        imagePullPolicy: Always

        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1000Mi

        ports:
          - containerPort: 27017

        volumeMounts:
        - mountPath: /data/db
          name: mongodb-data


  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
      annotations:
        volume.alpha.kubernetes.io/storage-class: default
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
