apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-deployment  

spec:
  replicas: 3
  strategy:
    type: RollingUpdate

  template:
    metadata:
      name: nodejs-pod # pod name
      labels: # pod metadata for info and service targetting
        name: nodejs-pod
        group: application

    spec:                                     
      containers:
      - name: nodejs-container # container name
        image: docker.io/darkxeno/nodejs-pod:0.9.0 # docker url: repository, image and tag

        resources: # resources requirements and limits, important for scheduling (distribution inside of the cluster)
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 300m
            memory: 200Mi

        livenessProbe:
          httpGet:
            path: /api/is-alive
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /api/is-ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10            
            
        ports:
          - name: koa-port
            containerPort: 3000

        env:
          - name: PORT
            value: '3000'